-- POXY CLUB P0: Club XP, Flash Events, Elite Bounties, Vault Progress, Server VIP Roll
-- Apply after migration_poxy_world_2.sql

-- -----------------------------------------------------------------------------
-- 1. Profile club progression
-- -----------------------------------------------------------------------------
alter table public.profiles
  add column if not exists club_xp integer not null default 0,
  add column if not exists club_level integer not null default 1,
  add column if not exists total_vip_opens integer not null default 0,
  add column if not exists club_cosmetic_tokens integer not null default 0,
  add column if not exists club_vault_progress integer not null default 0,
  add column if not exists club_vault_claimed integer not null default 0;

-- -----------------------------------------------------------------------------
-- 2. Club flash events (global 15-min mythic boost windows)
-- -----------------------------------------------------------------------------
create table if not exists public.club_flash_events (
  id bigint generated by default as identity primary key,
  starts_at timestamptz not null default now(),
  ends_at timestamptz not null,
  tier_boost_multiplier numeric(6,3) not null default 3.000,
  created_at timestamptz not null default now()
);

create index if not exists club_flash_events_ends_at_idx on public.club_flash_events (ends_at desc);

-- -----------------------------------------------------------------------------
-- 3. Club elite bounties (daily, separate from global daily_quests)
-- -----------------------------------------------------------------------------
create table if not exists public.club_bounties (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  quest_key text not null,
  progress integer not null default 0,
  goal integer not null,
  reward_tokens integer not null default 1,
  reward_xp integer not null default 0,
  claimed boolean not null default false,
  reset_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint club_bounties_user_key_day_unique unique (user_id, quest_key, reset_at)
);

create index if not exists club_bounties_user_reset_idx on public.club_bounties (user_id, reset_at desc);

-- -----------------------------------------------------------------------------
-- 4. Case open log (foundation for heatmap)
-- -----------------------------------------------------------------------------
create table if not exists public.case_open_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  case_type text not null check (case_type in ('standard', 'vip')),
  poxy_tier text not null,
  flash_active boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists case_open_events_created_idx on public.case_open_events (created_at desc);

-- -----------------------------------------------------------------------------
-- Helpers: club level from XP
-- -----------------------------------------------------------------------------
create or replace function public.club_level_for_xp(p_xp integer)
returns integer
language sql
immutable
as $$
  select greatest(1, least(10,
    case
      when p_xp < 100 then 1
      when p_xp < 250 then 2
      when p_xp < 500 then 3
      when p_xp < 800 then 4
      when p_xp < 1200 then 5
      when p_xp < 1700 then 6
      when p_xp < 2300 then 7
      when p_xp < 3000 then 8
      when p_xp < 3800 then 9
      else 10
    end
  ));
$$;

create or replace function public.club_discount_pct(p_level integer)
returns integer
language sql
immutable
as $$
  select least(25, 5 + greatest(0, coalesce(p_level, 1) - 1) * 2);
$$;

create or replace function public.club_xp_for_next_level(p_xp integer)
returns integer
language sql
immutable
as $$
  select case public.club_level_for_xp(p_xp)
    when 1 then 100 when 2 then 250 when 3 then 500 when 4 then 800 when 5 then 1200
    when 6 then 1700 when 7 then 2300 when 8 then 3000 when 9 then 3800 else 3800
  end;
$$;

-- -----------------------------------------------------------------------------
-- Grant club XP and recalc level
-- -----------------------------------------------------------------------------
create or replace function public.grant_club_xp(p_user_id uuid, p_amount integer)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_xp integer;
  v_level integer;
begin
  if auth.uid() is not null and auth.uid() is distinct from p_user_id then
    return jsonb_build_object('ok', false, 'error', 'Not authorized');
  end if;

  if p_amount is null or p_amount <= 0 then
    select club_xp, club_level into v_xp, v_level from public.profiles where id = p_user_id;
    return jsonb_build_object('ok', true, 'club_xp', coalesce(v_xp, 0), 'club_level', coalesce(v_level, 1));
  end if;

  update public.profiles
  set club_xp = club_xp + p_amount
  where id = p_user_id
  returning club_xp into v_xp;

  v_level := public.club_level_for_xp(v_xp);
  update public.profiles set club_level = v_level where id = p_user_id;

  return jsonb_build_object('ok', true, 'club_xp', v_xp, 'club_level', v_level, 'granted', p_amount);
end;
$$;

grant execute on function public.grant_club_xp(uuid, integer) to authenticated;

-- -----------------------------------------------------------------------------
-- Active / spawn flash event
-- -----------------------------------------------------------------------------
create or replace function public.get_club_flash_status()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ev public.club_flash_events%rowtype;
begin
  select * into v_ev
  from public.club_flash_events
  where starts_at <= now() and ends_at > now()
  order by ends_at desc
  limit 1;

  if found then
    return jsonb_build_object(
      'active', true,
      'ends_at', v_ev.ends_at,
      'starts_at', v_ev.starts_at,
      'tier_boost_multiplier', v_ev.tier_boost_multiplier
    );
  end if;

  return jsonb_build_object('active', false);
end;
$$;

grant execute on function public.get_club_flash_status() to authenticated;

create or replace function public.spawn_club_flash_if_due()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ev public.club_flash_events%rowtype;
  v_last timestamptz;
begin
  select * into v_ev
  from public.club_flash_events
  where ends_at > now()
  order by ends_at desc
  limit 1;

  if found then
    return jsonb_build_object('active', true, 'ends_at', v_ev.ends_at, 'spawned', false);
  end if;

  select max(ends_at) into v_last from public.club_flash_events;
  if v_last is not null and v_last > now() - interval '36 hours' then
    return jsonb_build_object('active', false, 'spawned', false, 'next_eligible', v_last + interval '36 hours');
  end if;

  insert into public.club_flash_events (starts_at, ends_at, tier_boost_multiplier)
  values (now(), now() + interval '15 minutes', 3.0)
  returning * into v_ev;

  return jsonb_build_object(
    'active', true,
    'ends_at', v_ev.ends_at,
    'starts_at', v_ev.starts_at,
    'tier_boost_multiplier', v_ev.tier_boost_multiplier,
    'spawned', true
  );
end;
$$;

grant execute on function public.spawn_club_flash_if_due() to authenticated;

-- -----------------------------------------------------------------------------
-- Server-side VIP tier roll (flash boosts diamond + secret)
-- -----------------------------------------------------------------------------
create or replace function public.roll_vip_tier(p_user_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_boost numeric := 1.0;
  v_r double precision;
  v_w0 double precision := 0.400;
  v_w1 double precision := 0.300;
  v_w2 double precision := 0.180;
  v_w3 double precision := 0.090;
  v_w4 double precision := 0.025;
  v_w5 double precision := 0.005;
  v_sum double precision;
begin
  select coalesce(tier_boost_multiplier, 1.0) into v_boost
  from public.club_flash_events
  where starts_at <= now() and ends_at > now()
  order by ends_at desc
  limit 1;

  v_w4 := v_w4 * v_boost;
  v_w5 := v_w5 * v_boost;
  v_sum := v_w0 + v_w1 + v_w2 + v_w3 + v_w4 + v_w5;
  v_r := random() * v_sum;

  if v_r < v_w0 then return 'obsidian'; end if;
  v_r := v_r - v_w0;
  if v_r < v_w1 then return 'cursed'; end if;
  v_r := v_r - v_w1;
  if v_r < v_w2 then return 'souvenir'; end if;
  v_r := v_r - v_w2;
  if v_r < v_w3 then return 'stellar'; end if;
  v_r := v_r - v_w3;
  if v_r < v_w4 then return 'diamond'; end if;
  return 'secret';
end;
$$;

grant execute on function public.roll_vip_tier(uuid) to authenticated;

-- -----------------------------------------------------------------------------
-- open_vip_case v2: optional tier (server roll), XP, vault, bounties, logging
-- -----------------------------------------------------------------------------
create or replace function public.open_vip_case(
  p_user_id uuid,
  p_tier text default null,
  p_serial text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_price numeric := 5.00;
  v_balance numeric;
  v_vip_serial bigint;
  v_new_id uuid;
  v_is_member boolean;
  v_tier text;
  v_flash boolean := false;
  v_xp_gain integer := 25;
  v_level integer;
  v_discount integer;
begin
  if auth.uid() is distinct from p_user_id then
    return jsonb_build_object('ok', false, 'error', 'Not authorized');
  end if;

  select is_club_member, club_level into v_is_member, v_level from public.profiles where id = p_user_id;
  v_discount := public.club_discount_pct(coalesce(v_level, 1));
  v_price := round(v_price * (1 - v_discount::numeric / 100), 2);
  if not coalesce(v_is_member, false) then
    return jsonb_build_object('ok', false, 'error', 'VIP membership required');
  end if;

  if p_tier is null or btrim(p_tier) = '' then
    v_tier := public.roll_vip_tier(p_user_id);
  else
    v_tier := p_tier;
  end if;

  if v_tier not in ('obsidian','cursed','souvenir','stellar','diamond','secret') then
    return jsonb_build_object('ok', false, 'error', 'Invalid VIP tier');
  end if;

  select exists (
    select 1 from public.club_flash_events where starts_at <= now() and ends_at > now()
  ) into v_flash;

  select balance into v_balance from public.profiles where id = p_user_id for update;
  if v_balance is null or v_balance < v_price then
    return jsonb_build_object('ok', false, 'error', 'Insufficient Poxy Coins');
  end if;

  update public.profiles set balance = balance - v_price where id = p_user_id;

  update public.vip_serial_counter
  set next_serial = next_serial + 1
  where poxy_tier = v_tier
  returning next_serial - 1 into v_vip_serial;

  if v_vip_serial is null then
    insert into public.vip_serial_counter (poxy_tier, next_serial) values (v_tier, 2)
    on conflict (poxy_tier) do update set next_serial = public.vip_serial_counter.next_serial + 1
    returning next_serial - 1 into v_vip_serial;
  end if;

  insert into public.user_poxy (user_id, poxy_tier, serial_number, is_vip, vip_serial, case_origin)
  values (p_user_id, v_tier, coalesce(p_serial, 'VIP-' || lpad(v_vip_serial::text, 6, '0')), true, v_vip_serial, 'vip')
  returning id into v_new_id;

  update public.profiles
  set
    total_vip_opens = total_vip_opens + 1,
    club_vault_progress = club_vault_progress + 1
  where id = p_user_id;

  perform public.grant_club_xp(p_user_id, v_xp_gain);

  perform public.increment_club_bounty_progress(p_user_id, 'club_open_5_vip', 1);

  insert into public.case_open_events (user_id, case_type, poxy_tier, flash_active)
  values (p_user_id, 'vip', v_tier, v_flash);

  return jsonb_build_object(
    'ok', true,
    'new_id', v_new_id,
    'tier', v_tier,
    'vip_serial', v_vip_serial,
    'new_balance', v_balance - v_price,
    'club_xp_gain', v_xp_gain,
    'flash_active', v_flash
  );
end;
$$;

-- -----------------------------------------------------------------------------
-- Club bounties RPCs
-- -----------------------------------------------------------------------------
create or replace function public.ensure_club_bounties(p_user_id uuid)
returns setof public.club_bounties
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reset timestamptz := date_trunc('day', now() at time zone 'utc') + interval '1 day';
begin
  if auth.uid() is distinct from p_user_id then
    return;
  end if;

  insert into public.club_bounties (user_id, quest_key, progress, goal, reward_tokens, reward_xp, reset_at)
  values
    (p_user_id, 'club_open_5_vip', 0, 5, 3, 50, v_reset),
    (p_user_id, 'club_post_2_feed', 0, 2, 2, 30, v_reset),
    (p_user_id, 'club_vote_1_dao', 0, 1, 2, 25, v_reset),
    (p_user_id, 'club_visit_terminal', 0, 1, 1, 15, v_reset)
  on conflict (user_id, quest_key, reset_at) do nothing;

  return query
  select * from public.club_bounties
  where user_id = p_user_id and reset_at = v_reset
  order by id;
end;
$$;

grant execute on function public.ensure_club_bounties(uuid) to authenticated;

create or replace function public.increment_club_bounty_progress(
  p_user_id uuid,
  p_quest_key text,
  p_delta integer default 1
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reset timestamptz := date_trunc('day', now() at time zone 'utc') + interval '1 day';
  v_q public.club_bounties%rowtype;
begin
  perform public.ensure_club_bounties(p_user_id);

  update public.club_bounties
  set progress = least(goal, progress + greatest(0, coalesce(p_delta, 1)))
  where user_id = p_user_id and quest_key = p_quest_key and reset_at = v_reset
  returning * into v_q;

  if not found then
    return jsonb_build_object('ok', false, 'error', 'Bounty not active');
  end if;

  return jsonb_build_object(
    'ok', true,
    'progress', v_q.progress,
    'goal', v_q.goal,
    'completed', v_q.progress >= v_q.goal
  );
end;
$$;

grant execute on function public.increment_club_bounty_progress(uuid, text, integer) to authenticated;

create or replace function public.claim_club_bounty_reward(p_user_id uuid, p_bounty_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_q public.club_bounties%rowtype;
  v_xp jsonb;
begin
  if auth.uid() is distinct from p_user_id then
    return jsonb_build_object('ok', false, 'error', 'Not authorized');
  end if;

  select * into v_q from public.club_bounties where id = p_bounty_id and user_id = p_user_id for update;
  if not found then
    return jsonb_build_object('ok', false, 'error', 'Bounty not found');
  end if;
  if v_q.progress < v_q.goal then
    return jsonb_build_object('ok', false, 'error', 'Bounty not complete');
  end if;
  if v_q.claimed then
    return jsonb_build_object('ok', false, 'error', 'Already claimed');
  end if;

  update public.club_bounties set claimed = true where id = p_bounty_id;

  update public.profiles
  set club_cosmetic_tokens = club_cosmetic_tokens + v_q.reward_tokens
  where id = p_user_id;

  v_xp := public.grant_club_xp(p_user_id, v_q.reward_xp);

  return jsonb_build_object(
    'ok', true,
    'reward_tokens', v_q.reward_tokens,
    'reward_xp', v_q.reward_xp,
    'club_xp', v_xp->'club_xp',
    'club_level', v_xp->'club_level'
  );
end;
$$;

grant execute on function public.claim_club_bounty_reward(uuid, bigint) to authenticated;

-- -----------------------------------------------------------------------------
-- Mystery vault claim (every 10 VIP opens unlocks one slot, max 5)
-- -----------------------------------------------------------------------------
create or replace function public.claim_club_vault_slot(p_user_id uuid, p_slot integer)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_prog integer;
  v_claimed integer;
  v_required integer;
  v_balance numeric;
  v_tier text;
  v_vip_serial bigint;
  v_new_id uuid;
begin
  if auth.uid() is distinct from p_user_id then
    return jsonb_build_object('ok', false, 'error', 'Not authorized');
  end if;

  if p_slot < 0 or p_slot > 4 then
    return jsonb_build_object('ok', false, 'error', 'Invalid slot');
  end if;

  select club_vault_progress, club_vault_claimed into v_prog, v_claimed
  from public.profiles where id = p_user_id for update;

  v_required := (p_slot + 1) * 10;
  if v_prog < v_required then
    return jsonb_build_object('ok', false, 'error', 'Need '+v_required+' VIP opens', 'progress', v_prog);
  end if;

  if (v_claimed & (1 << p_slot)) > 0 then
    return jsonb_build_object('ok', false, 'error', 'Slot already claimed');
  end if;

  v_tier := public.roll_vip_tier(p_user_id);

  update public.vip_serial_counter
  set next_serial = next_serial + 1
  where poxy_tier = v_tier
  returning next_serial - 1 into v_vip_serial;

  if v_vip_serial is null then
    insert into public.vip_serial_counter (poxy_tier, next_serial) values (v_tier, 2)
    on conflict (poxy_tier) do update set next_serial = public.vip_serial_counter.next_serial + 1
    returning next_serial - 1 into v_vip_serial;
  end if;

  insert into public.user_poxy (user_id, poxy_tier, serial_number, is_vip, vip_serial, case_origin)
  values (p_user_id, v_tier, 'VAULT-' || lpad(v_vip_serial::text, 6, '0'), true, v_vip_serial, 'vip')
  returning id into v_new_id;

  update public.profiles
  set club_vault_claimed = v_claimed | (1 << p_slot)
  where id = p_user_id;

  perform public.grant_club_xp(p_user_id, 40);

  return jsonb_build_object('ok', true, 'tier', v_tier, 'new_id', v_new_id, 'slot', p_slot);
end;
$$;

grant execute on function public.claim_club_vault_slot(uuid, integer) to authenticated;

-- -----------------------------------------------------------------------------
-- Club status snapshot for UI
-- -----------------------------------------------------------------------------
create or replace function public.get_club_status(p_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_p public.profiles%rowtype;
  v_next integer;
begin
  if auth.uid() is distinct from p_user_id then
    return jsonb_build_object('ok', false, 'error', 'Not authorized');
  end if;

  select * into v_p from public.profiles where id = p_user_id;
  if not found then
    return jsonb_build_object('ok', false, 'error', 'Profile not found');
  end if;

  v_next := public.club_xp_for_next_level(coalesce(v_p.club_xp, 0));

  return jsonb_build_object(
    'ok', true,
    'club_xp', coalesce(v_p.club_xp, 0),
    'club_level', coalesce(v_p.club_level, 1),
    'club_xp_next', v_next,
    'discount_pct', public.club_discount_pct(coalesce(v_p.club_level, 1)),
    'total_vip_opens', coalesce(v_p.total_vip_opens, 0),
    'club_cosmetic_tokens', coalesce(v_p.club_cosmetic_tokens, 0),
    'club_vault_progress', coalesce(v_p.club_vault_progress, 0),
    'club_vault_claimed', coalesce(v_p.club_vault_claimed, 0)
  );
end;
$$;

grant execute on function public.get_club_status(uuid) to authenticated;

-- -----------------------------------------------------------------------------
-- RLS
-- -----------------------------------------------------------------------------
alter table public.club_flash_events enable row level security;
alter table public.club_bounties enable row level security;
alter table public.case_open_events enable row level security;

drop policy if exists club_flash_events_select_all on public.club_flash_events;
create policy club_flash_events_select_all on public.club_flash_events
  for select to authenticated using (true);

drop policy if exists club_flash_events_insert_founder on public.club_flash_events;
create policy club_flash_events_insert_founder on public.club_flash_events
  for insert to authenticated with check (public.is_founder());

drop policy if exists club_bounties_select_own on public.club_bounties;
create policy club_bounties_select_own on public.club_bounties
  for select to authenticated using (user_id = auth.uid() or public.is_founder());

drop policy if exists case_open_events_select_authenticated on public.case_open_events;
create policy case_open_events_select_authenticated on public.case_open_events
  for select to authenticated using (true);

grant select on public.club_flash_events to authenticated;
grant select on public.club_bounties to authenticated;
grant select on public.case_open_events to authenticated;
